spring.application.name=JWT

# Настройки базы данных H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Настройки JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Консоль H2 (доступна по адресу http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Настройки сервера
server.port=8081

# Логирование
logging.level.org.springframework.web=DEBUG
logging.level.com.web_site.JWT=DEBUG

jwt.secret=my-super-secret-jwt-key-that-must-be-at-least-256-bits-long-to-work-with-hs256-algorithm-properly
jwt.access-token-expiration=5000
jwt.refresh-token-expiration=300000
